import { readFile } from 'node:fs/promises';
import path from 'node:path';

// Registry of fal.ai video models exposed to the SPA's "Generate video"
// dialog. Each entry knows:
//   - which fal model id to call
//   - which storyboard inputs it consumes (required vs optional vs unused)
//   - how to assemble the input payload from already-uploaded fal URLs
//   - how to read the video URL back out of the result
//
// Adding a new model is a one-entry change: drop a record below, expose the
// id in the SPA picker, done. The orchestrator (src/web/falVideoGenerate.js)
// never branches on model id.
//
// The wider universe of fal.ai image-to-video endpoints (188 of them at last
// snapshot) is described by data/fal-models.json, regenerated by
// `npm run refresh:fal-models`. The SPA picker shows that whole catalog and
// flags entries that are wired up here (`is_registered: true`); others show
// as "Preview" and can't be submitted until someone adds a registry entry
// below. loadCatalog() at the bottom of this file merges the two.

export const INPUT_NEEDS = Object.freeze({
  REQUIRED: 'required',
  OPTIONAL: 'optional',
  UNUSED: 'unused',
});

// Maximum number of character "elements" we'll pass to Kling 3 Pro. The
// model's docs cap at a small number; we cap at 4 to match Kling's
// reference docs and to keep prompt size sane.
const MAX_ELEMENTS = 4;

// Cap a prompt to a model's documented hard limit. fal returns a validation
// error on long prompts; we silently truncate so a too-long text_prompt
// never blocks a render. Kling docs mention 2000 chars; we keep 1500 as a
// safety margin shared across models.
const PROMPT_HARD_CAP = 2000;
function capPrompt(s) {
  const t = String(s || '').trim();
  return t.length > PROMPT_HARD_CAP ? t.slice(0, PROMPT_HARD_CAP) : t;
}

// Map our input bundle to a "video URL" payload shape that every model in
// this registry can stitch from. The orchestrator hands every model the
// same bundle; each model picks the fields it needs.
//
// The bundle:
//   prompt:                string (markdown stripped, fal-cap applied)
//   startFrameUrl:         fal URL of storyboard.start_frame_id image
//   endFrameUrl:           fal URL of storyboard.end_frame_id image (or null)
//   characterSheetUrl:     fal URL of storyboard.character_sheet_image_id (or null)
//   characterElements:     [{ frontalUrl, referenceUrls: [] }] built from
//                          each character in characters_in_scene (capped)
//   referenceImageUrls:    fal URLs for each storyboard.reference_image_ids[]
//   audioUrl:              fal URL of storyboard.audio_file_id (or null)
//   durationSeconds:       integer 1..15
//   generateAudio:         boolean (only honored by models that support it)

export const VIDEO_MODELS = [
  {
    id: 'kling-3-pro',
    label: 'Kling 3 Pro',
    falModel: 'fal-ai/kling-video/v3/pro/image-to-video',
    description:
      'Image-to-video with start frame, optional end frame, character elements ' +
      '(built from characters_in_scene), and native audio synthesis from the prompt.',
    // Kling 3 Pro accepts integer-string durations 3..15.
    durations: ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'],
    defaultDuration: '5',
    supportsGenerateAudio: true,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.OPTIONAL,
      characterSheet: INPUT_NEEDS.UNUSED,
      characterElements: INPUT_NEEDS.OPTIONAL,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      const input = {
        prompt: capPrompt(bundle.prompt) || 'Cinematic shot.',
        start_image_url: bundle.startFrameUrl,
        duration: String(bundle.durationSeconds || 5),
        generate_audio: Boolean(bundle.generateAudio),
      };
      if (bundle.endFrameUrl) input.end_image_url = bundle.endFrameUrl;
      const elements = (bundle.characterElements || []).slice(0, MAX_ELEMENTS).map((el) => {
        const out = { frontal_image_url: el.frontalUrl };
        if (Array.isArray(el.referenceUrls) && el.referenceUrls.length) {
          out.reference_image_urls = el.referenceUrls;
        }
        return out;
      });
      if (elements.length) input.elements = elements;
      return input;
    },
    extractVideoUrl(data) {
      return data?.video?.url || data?.output || null;
    },
  },

  {
    id: 'veo-3-1-flf',
    label: 'Veo 3.1 (first-last-frame)',
    falModel: 'fal-ai/veo3.1/first-last-frame-to-video',
    description:
      'Best-in-class motion quality. Requires both start and end frames. ' +
      'Audio is generated from the prompt; cannot consume an input audio file.',
    durations: ['4', '6', '8'],
    defaultDuration: '8',
    supportsGenerateAudio: true,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.REQUIRED,
      characterSheet: INPUT_NEEDS.UNUSED,
      characterElements: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      return {
        prompt: capPrompt(bundle.prompt) || 'Cinematic shot.',
        first_frame_url: bundle.startFrameUrl,
        last_frame_url: bundle.endFrameUrl,
        duration: `${bundle.durationSeconds || 8}s`,
        generate_audio: Boolean(bundle.generateAudio),
      };
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'kling-avatar-v2-pro',
    label: 'Kling AI Avatar v2 Pro (lip-sync)',
    falModel: 'fal-ai/kling-video/ai-avatar/v2/pro',
    description:
      'True lip-sync. Takes one anchor image plus an audio file and animates a ' +
      'talking head matched to the audio. Ignores end frame and character elements.',
    // Duration follows the input audio length; the API has no duration knob.
    durations: [],
    defaultDuration: null,
    supportsGenerateAudio: false,
    inputs: {
      // Anchor image: the orchestrator prefers character_sheet_image_id when
      // present (closer crop of the speaking subject), else falls back to
      // start_frame_id. We mark startFrame REQUIRED so storyboards without
      // either anchor get rejected with a clear message.
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.OPTIONAL,
      characterElements: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.REQUIRED,
    },
    buildInput(bundle) {
      const input = {
        image_url: bundle.characterSheetUrl || bundle.startFrameUrl,
        audio_url: bundle.audioUrl,
      };
      const prompt = capPrompt(bundle.prompt);
      if (prompt) input.prompt = prompt;
      return input;
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'flashhead',
    label: 'Flashhead',
    falModel: 'fal-ai/flashhead',
    description:
      'Soul AI Lab Flashhead. Image-to-video where the prompt is delivered as the ' +
      "model's `text` field. Single anchor image, no end frame.",
    durations: [],
    defaultDuration: null,
    supportsGenerateAudio: false,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.UNUSED,
      characterElements: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      return {
        image_url: bundle.startFrameUrl,
        text: capPrompt(bundle.prompt) || 'Cinematic shot.',
      };
    },
    extractVideoUrl(data) {
      return data?.video?.url || data?.output?.url || null;
    },
  },
];

const MODELS_BY_ID = new Map(VIDEO_MODELS.map((m) => [m.id, m]));

export function getVideoModel(id) {
  return MODELS_BY_ID.get(String(id)) || null;
}

// Inputs the SPA dialog can use to drive UI affordances without re-deriving
// shape per model. Returns null when the id isn't registered.
export function describeVideoModel(id) {
  const m = getVideoModel(id);
  if (!m) return null;
  return {
    id: m.id,
    label: m.label,
    description: m.description,
    durations: m.durations,
    defaultDuration: m.defaultDuration,
    supportsGenerateAudio: m.supportsGenerateAudio,
    inputs: m.inputs,
  };
}

// Storyboard fields each input maps to; used by validateInputs and by the
// orchestrator when assembling the bundle.
const INPUT_TO_FIELD = Object.freeze({
  startFrame: 'start_frame_id',
  endFrame: 'end_frame_id',
  characterSheet: 'character_sheet_image_id',
  audio: 'audio_file_id',
});

// Human-readable label for missing-input errors.
const INPUT_LABEL = Object.freeze({
  startFrame: 'start frame',
  endFrame: 'end frame',
  characterSheet: 'character sheet',
  audio: 'audio',
});

// Validate that a storyboard has the inputs a chosen model requires.
// Returns an array of human-readable missing labels (empty when OK).
export function validateStoryboardInputs(model, storyboard) {
  const missing = [];
  for (const [inputKey, need] of Object.entries(model.inputs)) {
    if (need !== INPUT_NEEDS.REQUIRED) continue;
    if (inputKey === 'referenceImages') {
      // Accept reference_image_ids OR fall back to start_frame / character_sheet
      // — the orchestrator substitutes those when references are required but
      // none were explicitly attached.
      const ids = storyboard?.reference_image_ids;
      const haveExplicit = Array.isArray(ids) && ids.length > 0;
      const haveFallback = Boolean(
        storyboard?.start_frame_id || storyboard?.character_sheet_image_id,
      );
      if (!haveExplicit && !haveFallback) missing.push('reference images');
      continue;
    }
    const field = INPUT_TO_FIELD[inputKey];
    if (!field) continue; // characterElements has no single storyboard field
    if (!storyboard[field]) missing.push(INPUT_LABEL[inputKey] || inputKey);
  }
  return missing;
}

// ---------------------------------------------------------------------------
// Catalog (data/fal-models.json) — the wide list of i2v fal endpoints the SPA
// picker browses. Most catalog entries are "Preview" (no registry wiring);
// the few in VIDEO_MODELS are "Ready" and selectable for generation.
//
// Families in CATALOG_READY_PREFIXES additionally get a generic auto-wire
// path: when the model's required params are all things we know how to fill
// (start frame, end frame, reference images, character sheet, audio, prompt),
// synthesizeCatalogModel() builds a registry-shaped object on the fly and
// the picker promotes the row to Ready. This avoids hand-writing 50+ entries.

const CATALOG_PATH = path.join(process.cwd(), 'data', 'fal-models.json');

// Param-name sets — copies of the ones in scripts/cluster-fal-video-models.js.
// We can't import that script: it's a build tool that pulls in node:fs paths
// relative to cwd, and a tiny duplication is cheaper than the coupling.
const START_NAMES = new Set([
  'image_url', 'first_frame_url', 'start_image_url', 'first_image_url',
  'first_frame_image_url', 'start_frame', 'source_image_url', 'input_image_url',
]);
const END_NAMES = new Set([
  'end_image_url', 'last_frame_url', 'tail_image_url', 'end_frame', 'last_image_url',
]);
const REFERENCE_NAMES = new Set([
  'image_urls', 'ref_image_urls', 'reference_image_urls', 'input_image_urls',
  'reference_image_url', 'image_references', 'reference_video_urls',
]);
const CHARACTER_NAMES = new Set([
  'character', 'character_ids', 'character_orientation', 'multi_character',
  'subject_reference_image_url', 'character_image', 'character_sheet',
]);
const AUDIO_NAMES = new Set([
  'audio_url', 'audio_urls', 'driven_audio_url', 'audio_input',
  'voice_url', 'speech_url', 'first_audio_url', 'reference_audio_url',
  'second_audio_url', 'audio_file',
]);

// Family allowlist. An endpoint is in an allowed family if any path segment
// of its id equals (or starts with `<prefix>-` / `<prefix>/`) one of these.
// Segment-prefix matching avoids matching "swan*" via the "wan" prefix.
const CATALOG_READY_PREFIXES = [
  'ltx', 'grok-imagine', 'bytedance', 'wan', 'vidu',
  'veo3.1', 'kling', 'happy-horse', 'pixverse', 'pika', 'longcat', 'minimax',
];

function isAllowedFamily(endpointId) {
  if (!endpointId) return false;
  const segs = String(endpointId).toLowerCase().split('/');
  return segs.some((seg) =>
    CATALOG_READY_PREFIXES.some((p) => seg === p || seg.startsWith(p + '-')),
  );
}

// Generic-wireable iff every required param is either 'prompt' or covered by
// one of our name-sets. Models that need params we can't fill (e.g.
// template_id, video_url) stay Preview.
const UNIVERSAL_REQUIRED = new Set(['prompt']);
const ALL_MAPPED = new Set([
  ...START_NAMES,
  ...END_NAMES,
  ...REFERENCE_NAMES,
  ...CHARACTER_NAMES,
  ...AUDIO_NAMES,
]);

function canGenericWire(row) {
  const req = row?.inputs_required;
  if (!Array.isArray(req)) return false;
  return req.every((p) => UNIVERSAL_REQUIRED.has(p) || ALL_MAPPED.has(p));
}

function pickFirstParam(nameSet, allParams) {
  for (const name of allParams) if (nameSet.has(name)) return name;
  return null;
}

// Build a registry-shape model from a catalog row. The returned object has
// the same surface as VIDEO_MODELS entries so the orchestrator's loop in
// runVideoGenerationJob() works without branching.
function synthesizeCatalogModel(row) {
  const required = row.inputs_required || [];
  const optional = row.inputs_optional || [];
  // Iterate required first so we prefer required param names when a model
  // declares both (rare but possible).
  const allParams = [...required, ...optional];
  const allSet = new Set(allParams);

  const startParam = pickFirstParam(START_NAMES, allParams);
  const endParam = pickFirstParam(END_NAMES, allParams);
  const refParam = pickFirstParam(REFERENCE_NAMES, allParams);
  const charParam = pickFirstParam(CHARACTER_NAMES, allParams);
  const audioParam = pickFirstParam(AUDIO_NAMES, allParams);

  const supportsGenerateAudio = allSet.has('generate_audio');
  const hasDuration = allSet.has('duration');
  const durationsEnum = Array.isArray(row.durations_enum) ? row.durations_enum.map(String) : [];

  // Detect duration format from enum entries: '8s', '8.0', '8'.
  let durationFormat = 'int';
  if (durationsEnum.length) {
    const sample = durationsEnum[0];
    if (/s$/.test(sample)) durationFormat = 'suffix-s';
    else if (sample.includes('.')) durationFormat = 'float';
  }

  function formatDuration(seconds) {
    const n = Number(seconds);
    if (!Number.isFinite(n) || n <= 0) return null;
    if (durationFormat === 'suffix-s') return `${Math.round(n)}s`;
    if (durationFormat === 'float') return String(n.toFixed(1));
    return Math.round(n);
  }

  // Default duration: prefer the largest enum value if the API enforces one;
  // otherwise leave null (the orchestrator falls back to storyboard / 5s).
  const defaultDuration = durationsEnum.length ? durationsEnum[durationsEnum.length - 1] : null;

  function buildInput(bundle) {
    const input = { prompt: capPrompt(bundle.prompt) || 'Cinematic shot.' };
    if (startParam && bundle.startFrameUrl) input[startParam] = bundle.startFrameUrl;
    if (endParam && bundle.endFrameUrl) input[endParam] = bundle.endFrameUrl;
    if (charParam && bundle.characterSheetUrl) input[charParam] = bundle.characterSheetUrl;
    if (audioParam && bundle.audioUrl) input[audioParam] = bundle.audioUrl;
    if (refParam && Array.isArray(bundle.referenceImageUrls) && bundle.referenceImageUrls.length) {
      // Array-typed params end in `s`/`urls`; singular ones take one URL.
      if (refParam.endsWith('urls') || refParam.endsWith('_urls') || refParam.endsWith('s')) {
        input[refParam] = bundle.referenceImageUrls;
      } else {
        input[refParam] = bundle.referenceImageUrls[0];
      }
    }
    if (hasDuration) {
      const formatted = formatDuration(bundle.durationSeconds);
      if (formatted != null) input.duration = formatted;
    }
    if (supportsGenerateAudio) input.generate_audio = Boolean(bundle.generateAudio);
    return input;
  }

  function extractVideoUrl(data) {
    return (
      data?.video?.url ||
      data?.output?.url ||
      (typeof data?.output === 'string' ? data.output : null) ||
      data?.video_url ||
      data?.videos?.[0]?.url ||
      null
    );
  }

  return {
    id: row.endpoint_id,
    label: row.display_name || row.endpoint_id,
    falModel: row.endpoint_id,
    description:
      [row.model_lab, row.model_family].filter(Boolean).join(' · ') ||
      `Auto-wired from catalog. Required: ${required.join(', ') || '(none)'}.`,
    durations: durationsEnum,
    defaultDuration,
    supportsGenerateAudio,
    inputs: row.inputs || { ...DEFAULT_CATALOG_INPUTS },
    buildInput,
    extractVideoUrl,
    _synthetic: true,
  };
}

// Cache synthesized models so repeated jobs don't rebuild. Cleared at module
// scope so tests using `_resetForTests()` (none today, but easy to add) can
// reset; the catalog itself is also cheap to re-read so the cache is purely
// a per-process optimization.
const SYNTH_CACHE = new Map();

// Async lookup that consults the registry first, then falls back to the
// catalog manifest for endpoints in allowlisted families with generic-
// wireable inputs. Returns null when the id is unknown OR known but not
// auto-wireable (callers should treat both as "preview not ready").
export async function getVideoModelOrCatalog(id) {
  const registered = getVideoModel(id);
  if (registered) return registered;
  if (!id) return null;
  if (SYNTH_CACHE.has(id)) return SYNTH_CACHE.get(id);
  const cat = await loadCatalog();
  const row = cat.models.find((m) => m.endpoint_id === id);
  if (!row) return null;
  if (!isAllowedFamily(id)) return null;
  if (!canGenericWire(row)) return null;
  const model = synthesizeCatalogModel(row);
  SYNTH_CACHE.set(id, model);
  return model;
}

// Default `inputs` shape used when a catalog entry doesn't specify one
// (defensive — newer manifests always include it).
const DEFAULT_CATALOG_INPUTS = Object.freeze({
  startFrame: INPUT_NEEDS.UNUSED,
  endFrame: INPUT_NEEDS.UNUSED,
  characterSheet: INPUT_NEEDS.UNUSED,
  characterElements: INPUT_NEEDS.UNUSED,
  referenceImages: INPUT_NEEDS.UNUSED,
  audio: INPUT_NEEDS.UNUSED,
});

// Map a registered VIDEO_MODELS entry into the SPA-facing dialog shape (no
// buildInput / extractVideoUrl, but all the picker metadata).
function registryToDialogShape(m) {
  return {
    id: m.id,
    label: m.label,
    description: m.description,
    durations: m.durations,
    default_duration: m.defaultDuration,
    supports_generate_audio: m.supportsGenerateAudio,
    inputs: m.inputs,
  };
}

// Merge a catalog row + (optional) registered VIDEO_MODELS entry into the
// dialog row shape. Registered fields win over catalog ones because the
// registry's hand-tuned description / duration list is more useful in the
// dropdown than the raw OpenAPI extraction.
//
// Rows in CATALOG_READY_PREFIXES whose required params are all in our
// name-sets get promoted to is_registered=true with id=endpoint_id; the
// orchestrator resolves these via getVideoModelOrCatalog() at submit time.
function mergeCatalogRow(catalogRow, registered) {
  const base = {
    endpoint_id: catalogRow.endpoint_id,
    display_name: catalogRow.display_name,
    model_lab: catalogRow.model_lab,
    model_family: catalogRow.model_family,
    capabilities: catalogRow.capabilities,
    capability_score: catalogRow.capability_score,
    resolutions: catalogRow.resolutions || [],
    aspect_ratios: catalogRow.aspect_ratios || [],
    max_seconds: catalogRow.max_seconds,
    max_seconds_source: catalogRow.max_seconds_source,
    durations_enum: catalogRow.durations_enum || [],
    supports_generate_audio: Boolean(catalogRow.supports_generate_audio),
    price_text: catalogRow.price_text || null,
    price_min_usd: catalogRow.price_min_usd ?? null,
    inputs: catalogRow.inputs || { ...DEFAULT_CATALOG_INPUTS },
    inputs_required: Array.isArray(catalogRow.inputs_required) ? catalogRow.inputs_required : [],
    inputs_optional: Array.isArray(catalogRow.inputs_optional) ? catalogRow.inputs_optional : [],
    added_at: catalogRow.added_at || null,
    is_registered: false,
    id: null,
    label: catalogRow.display_name,
    description: null,
    durations: catalogRow.durations_enum || [],
    default_duration: null,
  };
  if (registered) {
    const r = registryToDialogShape(registered);
    return {
      ...base,
      is_registered: true,
      id: r.id,
      label: r.label,
      description: r.description,
      durations: r.durations,
      default_duration: r.default_duration,
      supports_generate_audio: r.supports_generate_audio,
      inputs: r.inputs,
    };
  }
  if (isAllowedFamily(catalogRow.endpoint_id) && canGenericWire(catalogRow)) {
    return {
      ...base,
      is_registered: true,
      id: catalogRow.endpoint_id,
      description:
        [catalogRow.model_lab, catalogRow.model_family].filter(Boolean).join(' · ') ||
        'Auto-wired from catalog.',
    };
  }
  return base;
}

// Stub-shape catalog row for a registered model that isn't in the manifest
// (e.g. data/fal-models.json never generated, or the model was hand-added).
function registryStubRow(m) {
  return {
    endpoint_id: m.falModel,
    display_name: m.label,
    model_lab: null,
    model_family: null,
    capabilities: capabilitiesFromInputs(m.inputs),
    capability_score: capabilityScoreFromInputs(m.inputs),
    resolutions: [],
    aspect_ratios: [],
    max_seconds: null,
    max_seconds_source: null,
    durations_enum: Array.isArray(m.durations) ? m.durations.map(String) : [],
    supports_generate_audio: Boolean(m.supportsGenerateAudio),
    price_text: null,
    price_min_usd: null,
    inputs: m.inputs,
  };
}

function capabilitiesFromInputs(inputs) {
  const i = inputs || {};
  return {
    start_frame: i.startFrame === INPUT_NEEDS.REQUIRED || i.startFrame === INPUT_NEEDS.OPTIONAL,
    end_frame: i.endFrame === INPUT_NEEDS.REQUIRED || i.endFrame === INPUT_NEEDS.OPTIONAL,
    reference_images: i.referenceImages === INPUT_NEEDS.REQUIRED || i.referenceImages === INPUT_NEEDS.OPTIONAL,
    character_sheet: i.characterSheet === INPUT_NEEDS.REQUIRED || i.characterSheet === INPUT_NEEDS.OPTIONAL,
    lip_sync: i.audio === INPUT_NEEDS.REQUIRED || i.audio === INPUT_NEEDS.OPTIONAL,
  };
}

function capabilityScoreFromInputs(inputs) {
  const c = capabilitiesFromInputs(inputs);
  return Object.values(c).filter(Boolean).length;
}

// Read the catalog manifest from disk and merge against VIDEO_MODELS. Returns
// `{ generated_at, catalog_error, models: [...] }`. Cheap enough (~200 KB
// JSON parse) to run per request — no in-memory cache for MVP.
export async function loadCatalog() {
  let catalog = null;
  let catalogError = null;
  try {
    const text = await readFile(CATALOG_PATH, 'utf8');
    catalog = JSON.parse(text);
  } catch (e) {
    if (e?.code === 'ENOENT') {
      catalogError = 'Catalog not generated yet. Run: npm run refresh:fal-models';
    } else {
      catalogError = `Catalog read failed: ${e.message}`;
    }
  }

  const registryByEndpoint = new Map(VIDEO_MODELS.map((m) => [m.falModel, m]));
  const seenEndpoints = new Set();
  const out = [];

  if (catalog?.models?.length) {
    for (const row of catalog.models) {
      const registered = registryByEndpoint.get(row.endpoint_id) || null;
      out.push(mergeCatalogRow(row, registered));
      seenEndpoints.add(row.endpoint_id);
    }
  }
  // Append registered models not present in the manifest (defensive — also
  // the no-catalog fallback: every registry entry surfaces as a Ready row).
  for (const m of VIDEO_MODELS) {
    if (seenEndpoints.has(m.falModel)) continue;
    out.push(mergeCatalogRow(registryStubRow(m), m));
  }

  return {
    generated_at: catalog?.generated_at || null,
    catalog_error: catalogError,
    models: out,
  };
}
