import { readFile } from 'node:fs/promises';
import path from 'node:path';

import { RES_TO_DIMS, describePricing, parseCatalogPriceText } from './videoPricing.js';

function resolutionToDims(resolution) {
  if (!resolution) return null;
  const key = String(resolution).toLowerCase();
  return RES_TO_DIMS[key] || RES_TO_DIMS[String(resolution)] || null;
}

// Registry of fal.ai video models exposed to the SPA's "Generate video"
// dialog. Each entry knows:
//   - which fal model id to call
//   - which storyboard inputs it consumes (required vs optional vs unused)
//   - how to assemble the input payload from already-uploaded fal URLs
//   - how to read the video URL back out of the result
//
// Adding a new model is a one-entry change: drop a record below, expose the
// id in the SPA picker, done. The orchestrator (src/web/falVideoGenerate.js)
// never branches on model id.
//
// The wider universe of fal.ai image-to-video endpoints (188 of them at last
// snapshot) is described by data/fal-models.json, regenerated by
// `npm run refresh:fal-models`. The SPA picker shows that whole catalog and
// flags entries that are wired up here (`is_registered: true`); others show
// as "Preview" and can't be submitted until someone adds a registry entry
// below. loadCatalog() at the bottom of this file merges the two.

export const INPUT_NEEDS = Object.freeze({
  REQUIRED: 'required',
  OPTIONAL: 'optional',
  UNUSED: 'unused',
});

// Cap a prompt to a model's documented hard limit. fal returns a validation
// error on long prompts; we silently truncate so a too-long text_prompt
// never blocks a render. Kling docs mention 2000 chars; we keep 1500 as a
// safety margin shared across models.
const PROMPT_HARD_CAP = 2000;
function capPrompt(s) {
  const t = String(s || '').trim();
  return t.length > PROMPT_HARD_CAP ? t.slice(0, PROMPT_HARD_CAP) : t;
}

// Map our input bundle to a "video URL" payload shape that every model in
// this registry can stitch from. The orchestrator hands every model the
// same bundle; each model picks the fields it needs. Every image URL in the
// bundle comes from an image explicitly attached to the storyboard row —
// nothing is auto-loaded from character documents or beat images.
//
// The bundle:
//   prompt:                string (markdown stripped, fal-cap applied)
//   startFrameUrl:         fal URL of storyboard.start_frame_id image
//   endFrameUrl:           fal URL of storyboard.end_frame_id image (or null)
//   characterSheetUrl:     fal URL of storyboard.character_sheet_image_id (or null)
//   referenceImageUrls:    fal URLs for each storyboard.reference_image_ids[]
//   audioUrl:              fal URL of storyboard.audio_file_id (or null)
//   videoUrl:              fal URL of storyboard.video_upload_file_id (or null)
//   durationSeconds:       integer 1..15
//   generateAudio:         boolean (only honored by models that support it)

export const VIDEO_MODELS = [
  {
    id: 'kling-3-pro',
    label: 'Kling 3 Pro',
    pricingId: 'kling-3-pro',
    falModel: 'fal-ai/kling-video/v3/pro/image-to-video',
    description:
      'Image-to-video with start frame, optional end frame, optional pinned ' +
      'character sheet (passed as a single Kling element), and native audio ' +
      'synthesis from the prompt.',
    // Kling 3 Pro accepts integer-string durations 3..15.
    durations: ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'],
    defaultDuration: '5',
    supportsGenerateAudio: true,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.OPTIONAL,
      characterSheet: INPUT_NEEDS.OPTIONAL,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
      videoInput: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      const input = {
        prompt: capPrompt(bundle.prompt) || 'Cinematic shot.',
        start_image_url: bundle.startFrameUrl,
        duration: String(bundle.durationSeconds || 5),
        generate_audio: Boolean(bundle.generateAudio),
      };
      if (bundle.endFrameUrl) input.end_image_url = bundle.endFrameUrl;
      if (bundle.characterSheetUrl) {
        input.elements = [{ frontal_image_url: bundle.characterSheetUrl }];
      }
      return input;
    },
    extractVideoUrl(data) {
      return data?.video?.url || data?.output || null;
    },
  },

  {
    id: 'veo-3-1-flf',
    label: 'Veo 3.1 (first-last-frame)',
    pricingId: 'veo-3-1-flf',
    falModel: 'fal-ai/veo3.1/first-last-frame-to-video',
    description:
      'Best-in-class motion quality. Requires both start and end frames. ' +
      'Audio is generated from the prompt; cannot consume an input audio file.',
    durations: ['4', '6', '8'],
    defaultDuration: '8',
    supportsGenerateAudio: true,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.REQUIRED,
      characterSheet: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
      videoInput: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      const input = {
        prompt: capPrompt(bundle.prompt) || 'Cinematic shot.',
        first_frame_url: bundle.startFrameUrl,
        last_frame_url: bundle.endFrameUrl,
        duration: `${bundle.durationSeconds || 8}s`,
        generate_audio: Boolean(bundle.generateAudio),
      };
      if (bundle.resolution) input.resolution = String(bundle.resolution);
      return input;
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'kling-avatar-v2-pro',
    label: 'Kling AI Avatar v2 Pro (lip-sync)',
    pricingId: 'kling-avatar-v2-pro',
    falModel: 'fal-ai/kling-video/ai-avatar/v2/pro',
    description:
      'True lip-sync. Takes one anchor image plus an audio file and animates a ' +
      'talking head matched to the audio. Ignores end frame and character elements.',
    // Duration follows the input audio length; the API has no duration knob.
    durations: [],
    defaultDuration: null,
    supportsGenerateAudio: false,
    inputs: {
      // Anchor image: the orchestrator prefers character_sheet_image_id when
      // present (closer crop of the speaking subject), else falls back to
      // start_frame_id. We mark startFrame REQUIRED so storyboards without
      // either anchor get rejected with a clear message.
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.OPTIONAL,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.REQUIRED,
      videoInput: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      const input = {
        image_url: bundle.characterSheetUrl || bundle.startFrameUrl,
        audio_url: bundle.audioUrl,
      };
      const prompt = capPrompt(bundle.prompt);
      if (prompt) input.prompt = prompt;
      return input;
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'flashhead',
    label: 'Flashhead',
    pricingId: 'flashhead',
    falModel: 'fal-ai/flashhead',
    description:
      'Soul AI Lab Flashhead. Image-to-video where the prompt is delivered as the ' +
      "model's `text` field. Single anchor image, no end frame.",
    durations: [],
    defaultDuration: null,
    supportsGenerateAudio: false,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
      videoInput: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      return {
        image_url: bundle.startFrameUrl,
        text: capPrompt(bundle.prompt) || 'Cinematic shot.',
      };
    },
    extractVideoUrl(data) {
      return data?.video?.url || data?.output?.url || null;
    },
  },

  {
    id: 'sora-2',
    label: 'Sora 2',
    pricingId: 'sora-2',
    falModel: 'fal-ai/sora-2/image-to-video',
    description:
      'OpenAI Sora 2 image-to-video. Strong motion and prompt adherence. ' +
      'No native audio synthesis.',
    durations: ['4', '8', '12', '16', '20'],
    defaultDuration: '8',
    supportsGenerateAudio: false,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
      videoInput: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      return {
        prompt: capPrompt(bundle.prompt) || 'Cinematic shot.',
        image_url: bundle.startFrameUrl,
        duration: String(bundle.durationSeconds || 8),
        aspect_ratio: bundle.aspectRatio ? String(bundle.aspectRatio) : 'auto',
        resolution: bundle.resolution ? String(bundle.resolution) : 'auto',
      };
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'sora-2-v2v-remix',
    label: 'Sora 2 — Video Remix',
    pricingId: 'sora-2-v2v-remix',
    falModel: 'fal-ai/sora-2/video-to-video/remix',
    description:
      'OpenAI Sora 2 video-to-video remix. Takes an existing Sora-generated ' +
      'video and a prompt and rerenders the clip in a new style. NOTE: the ' +
      'fal endpoint requires a Sora `video_id` from a previous Sora ' +
      'generation, not an arbitrary uploaded clip — the call will be ' +
      'rejected if the uploaded source was not produced by Sora.',
    durations: [],
    defaultDuration: null,
    supportsGenerateAudio: false,
    inputs: {
      startFrame: INPUT_NEEDS.UNUSED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
      videoInput: INPUT_NEEDS.REQUIRED,
    },
    buildInput(bundle) {
      return {
        prompt: capPrompt(bundle.prompt) || 'Restyle the video.',
        // fal expects a Sora-side video_id; we pass the uploaded URL so the
        // server-side validator returns a meaningful error if it isn't one.
        video_id: bundle.videoUrl,
      };
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'luma-ray-2-modify',
    label: 'Luma Ray 2 — Modify',
    pricingId: 'luma-ray-2-modify',
    falModel: 'fal-ai/luma-dream-machine/ray-2/modify',
    description:
      'Luma Dream Machine Ray 2 video-to-video restyle. Modifies an uploaded ' +
      'clip via prompt and optional first-frame reference image. Strong ' +
      'flagship for general v2v transforms.',
    durations: [],
    defaultDuration: null,
    supportsGenerateAudio: false,
    inputs: {
      startFrame: INPUT_NEEDS.OPTIONAL,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
      videoInput: INPUT_NEEDS.REQUIRED,
    },
    buildInput(bundle) {
      const input = {
        video_url: bundle.videoUrl,
      };
      const prompt = capPrompt(bundle.prompt);
      if (prompt) input.prompt = prompt;
      // Optional reference image: the start frame, when present, anchors the
      // first frame of the modified video.
      if (bundle.startFrameUrl) input.image_url = bundle.startFrameUrl;
      return input;
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'sync-lipsync-v2',
    label: 'Sync Lipsync v2',
    pricingId: 'sync-lipsync-v2',
    falModel: 'fal-ai/sync-lipsync/v2',
    description:
      'Industry-standard lip-sync. Takes a video of a talking subject plus ' +
      'an audio track and re-syncs the mouth movements to the new audio. ' +
      'Reuses the storyboard audio_file_id as the driving audio.',
    durations: [],
    defaultDuration: null,
    supportsGenerateAudio: false,
    inputs: {
      startFrame: INPUT_NEEDS.UNUSED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.REQUIRED,
      videoInput: INPUT_NEEDS.REQUIRED,
    },
    buildInput(bundle) {
      return {
        video_url: bundle.videoUrl,
        audio_url: bundle.audioUrl,
      };
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'decart-lucy-edit-pro',
    label: 'Decart Lucy Edit Pro',
    pricingId: 'decart-lucy-edit-pro',
    falModel: 'decart/lucy-edit/pro',
    description:
      'Decart Lucy Edit Pro video-to-video. Fast restyle/edit driven by a ' +
      'text prompt — good budget alternative for general v2v transforms.',
    durations: [],
    defaultDuration: null,
    supportsGenerateAudio: false,
    inputs: {
      startFrame: INPUT_NEEDS.UNUSED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
      videoInput: INPUT_NEEDS.REQUIRED,
    },
    buildInput(bundle) {
      return {
        video_url: bundle.videoUrl,
        prompt: capPrompt(bundle.prompt) || 'Restyle the video.',
      };
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'sora-2-pro',
    label: 'Sora 2 Pro',
    pricingId: 'sora-2-pro',
    falModel: 'fal-ai/sora-2/image-to-video/pro',
    description:
      'OpenAI Sora 2 Pro image-to-video. Same input shape as Sora 2; adds ' +
      '1080p / true_1080p resolutions.',
    durations: ['4', '8', '12', '16', '20'],
    defaultDuration: '8',
    supportsGenerateAudio: false,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
      videoInput: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      return {
        prompt: capPrompt(bundle.prompt) || 'Cinematic shot.',
        image_url: bundle.startFrameUrl,
        duration: String(bundle.durationSeconds || 8),
        aspect_ratio: bundle.aspectRatio ? String(bundle.aspectRatio) : 'auto',
        resolution: bundle.resolution ? String(bundle.resolution) : 'auto',
      };
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },
];

const MODELS_BY_ID = new Map(VIDEO_MODELS.map((m) => [m.id, m]));

export function getVideoModel(id) {
  return MODELS_BY_ID.get(String(id)) || null;
}

// Inputs the SPA dialog can use to drive UI affordances without re-deriving
// shape per model. Returns null when the id isn't registered.
export function describeVideoModel(id) {
  const m = getVideoModel(id);
  if (!m) return null;
  return {
    id: m.id,
    label: m.label,
    description: m.description,
    durations: m.durations,
    defaultDuration: m.defaultDuration,
    supportsGenerateAudio: m.supportsGenerateAudio,
    inputs: m.inputs,
    pricing: m.pricingId ? describePricing(m.pricingId) : null,
  };
}

// Human-readable label for missing-input errors.
const INPUT_LABEL = Object.freeze({
  startFrame: 'start frame',
  endFrame: 'end frame',
  characterSheet: 'character sheet',
  audio: 'audio',
  videoInput: 'uploaded video',
});

function dedupeIds(ids) {
  const seen = new Set();
  const out = [];
  for (const id of ids) {
    if (id == null) continue;
    const key = String(id);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(id);
  }
  return out;
}

// Resolve which of a storyboard's frame-pool images fill the chosen model's
// image slots (start_frame / end_frame / reference list).
//
// The start/end distinction is no longer stored — it is decided here, at
// generation time. `requested` is the optional per-generation override the SPA
// sends as `frame_assignment` ({ start_frame, end_frame, ref }); any id it
// names must be one of the pool's frame images (unknown ids are dropped). For
// any model-accepted slot the request omits, we fall back to an order-based
// default:
//   - startFrame → the first frame image
//   - endFrame   → the first frame image not already used as startFrame
//   - reference  → every frame image not used as start/end (for a model with no
//                  start/end slot of its own, that is ALL frames, in order),
//                  preserving the old fold-frames-into-refs behavior.
//
// Returns { startFrameId, endFrameId, referenceImageIds } with original id
// values (ObjectId or string) so downstream GridFS lookups still accept them.
export function resolveFrameAssignment(model, storyboard, requested = {}) {
  const needs = model?.inputs || {};
  const accepts = (key) => needs[key] && needs[key] !== INPUT_NEEDS.UNUSED;
  const frames = Array.isArray(storyboard?.frames) ? storyboard.frames : [];
  const frameImageIds = frames.map((f) => f?.image_id).filter(Boolean);
  const validKeys = new Set(frameImageIds.map((x) => String(x)));
  const resolveId = (id) =>
    id != null && validKeys.has(String(id))
      ? frameImageIds.find((x) => String(x) === String(id))
      : null;
  const req = requested && typeof requested === 'object' ? requested : {};

  let startFrameId = null;
  let endFrameId = null;
  let referenceImageIds = [];

  if (accepts('startFrame')) {
    startFrameId =
      req.start_frame !== undefined
        ? resolveId(req.start_frame)
        : frameImageIds[0] || null;
  }
  if (accepts('endFrame')) {
    endFrameId =
      req.end_frame !== undefined
        ? resolveId(req.end_frame)
        : frameImageIds.find((x) => String(x) !== String(startFrameId)) || null;
  }
  if (accepts('referenceImages')) {
    if (req.ref !== undefined) {
      const list = Array.isArray(req.ref) ? req.ref : [];
      referenceImageIds = dedupeIds(list.map(resolveId).filter(Boolean));
    } else {
      const used = new Set([startFrameId, endFrameId].filter(Boolean).map(String));
      referenceImageIds = dedupeIds(
        frameImageIds.filter((x) => !used.has(String(x))),
      );
    }
  }
  return { startFrameId, endFrameId, referenceImageIds };
}

// Validate that a resolved frame assignment (plus the storyboard's media)
// satisfies the inputs the chosen model requires. Returns an array of
// human-readable missing labels (empty when OK). `assignment` is the output of
// resolveFrameAssignment; `storyboard` supplies audio / uploaded-video media.
export function validateAssignment(model, assignment, storyboard = {}) {
  const missing = [];
  const a = assignment || {};
  for (const [inputKey, need] of Object.entries(model.inputs)) {
    if (need !== INPUT_NEEDS.REQUIRED) continue;
    if (inputKey === 'startFrame') {
      if (!a.startFrameId) missing.push(INPUT_LABEL.startFrame);
    } else if (inputKey === 'endFrame') {
      if (!a.endFrameId) missing.push(INPUT_LABEL.endFrame);
    } else if (inputKey === 'referenceImages') {
      if (!(a.referenceImageIds || []).length) missing.push('reference images');
    } else if (inputKey === 'characterSheet') {
      missing.push(INPUT_LABEL.characterSheet);
    } else if (inputKey === 'audio') {
      if (!storyboard.audio_file_id) missing.push(INPUT_LABEL.audio);
    } else if (inputKey === 'videoInput') {
      if (!storyboard.video_upload_file_id) missing.push(INPUT_LABEL.videoInput);
    }
  }
  return missing;
}

// ---------------------------------------------------------------------------
// Catalog (data/fal-models.json) — the wide list of i2v fal endpoints the SPA
// picker browses. Most catalog entries are "Preview" (no registry wiring);
// the few in VIDEO_MODELS are "Ready" and selectable for generation.
//
// Families in CATALOG_READY_PREFIXES additionally get a generic auto-wire
// path: when the model's required params are all things we know how to fill
// (start frame, end frame, reference images, character sheet, audio, prompt),
// synthesizeCatalogModel() builds a registry-shaped object on the fly and
// the picker promotes the row to Ready. This avoids hand-writing 50+ entries.

const CATALOG_PATH = path.join(process.cwd(), 'data', 'fal-models.json');

// Param-name sets — copies of the ones in scripts/cluster-fal-video-models.js.
// We can't import that script: it's a build tool that pulls in node:fs paths
// relative to cwd, and a tiny duplication is cheaper than the coupling.
const START_NAMES = new Set([
  'image_url', 'first_frame_url', 'start_image_url', 'first_image_url',
  'first_frame_image_url', 'start_frame', 'source_image_url', 'input_image_url',
]);
const END_NAMES = new Set([
  'end_image_url', 'last_frame_url', 'tail_image_url', 'end_frame', 'last_image_url',
]);
const REFERENCE_NAMES = new Set([
  'image_urls', 'ref_image_urls', 'reference_image_urls', 'input_image_urls',
  'reference_image_url', 'image_references', 'reference_video_urls',
]);
const CHARACTER_NAMES = new Set([
  'character', 'character_ids', 'character_orientation', 'multi_character',
  'subject_reference_image_url', 'character_image', 'character_sheet',
]);
const AUDIO_NAMES = new Set([
  'audio_url', 'audio_urls', 'driven_audio_url', 'audio_input',
  'voice_url', 'speech_url', 'first_audio_url', 'reference_audio_url',
  'second_audio_url', 'audio_file',
]);
const VIDEO_INPUT_NAMES = new Set([
  'video_url', 'source_video_url', 'mask_video_url', 'videos', 'video',
  'driving_video_url', 'reference_pose_video_url',
]);

// Family allowlist. An endpoint is in an allowed family if any path segment
// of its id equals (or starts with `<prefix>-` / `<prefix>/`) one of these.
// Segment-prefix matching avoids matching "swan*" via the "wan" prefix.
const CATALOG_READY_PREFIXES = [
  'ltx', 'grok-imagine', 'bytedance', 'wan', 'vidu',
  'veo3.1', 'kling', 'happy-horse', 'pixverse', 'pika', 'longcat', 'minimax',
  // Video-to-video families
  'decart', 'luma-dream-machine', 'sync', 'topaz', 'rife', 'sora-2',
];

function isAllowedFamily(endpointId) {
  if (!endpointId) return false;
  const segs = String(endpointId).toLowerCase().split('/');
  return segs.some((seg) =>
    CATALOG_READY_PREFIXES.some((p) => seg === p || seg.startsWith(p + '-')),
  );
}

// Generic-wireable iff every required param is either 'prompt' or covered by
// one of our name-sets. Models that need params we can't fill (e.g.
// template_id, video_url) stay Preview.
const UNIVERSAL_REQUIRED = new Set(['prompt']);
const ALL_MAPPED = new Set([
  ...START_NAMES,
  ...END_NAMES,
  ...REFERENCE_NAMES,
  ...CHARACTER_NAMES,
  ...AUDIO_NAMES,
  ...VIDEO_INPUT_NAMES,
]);

function canGenericWire(row) {
  const req = row?.inputs_required;
  if (!Array.isArray(req)) return false;
  return req.every((p) => UNIVERSAL_REQUIRED.has(p) || ALL_MAPPED.has(p));
}

function pickFirstParam(nameSet, allParams) {
  for (const name of allParams) if (nameSet.has(name)) return name;
  return null;
}

// fal types plural-named params ('audio_urls', 'image_urls', 'video_urls',
// 'videos') as lists and singular ones ('audio_url', 'video_url') as scalars.
// A trailing 's' reliably separates the two across our START/END/REFERENCE/
// AUDIO/VIDEO name-sets, so we wrap a single source URL into a one-element
// array for list params (otherwise fal rejects the scalar with a 422 list_type).
function isListParam(name) {
  return typeof name === 'string' && /s$/.test(name);
}

// Build a registry-shape model from a catalog row. The returned object has
// the same surface as VIDEO_MODELS entries so the orchestrator's loop in
// runVideoGenerationJob() works without branching.
function synthesizeCatalogModel(row) {
  const required = row.inputs_required || [];
  const optional = row.inputs_optional || [];
  // Iterate required first so we prefer required param names when a model
  // declares both (rare but possible).
  const allParams = [...required, ...optional];
  const allSet = new Set(allParams);

  const startParam = pickFirstParam(START_NAMES, allParams);
  const endParam = pickFirstParam(END_NAMES, allParams);
  const refParam = pickFirstParam(REFERENCE_NAMES, allParams);
  const charParam = pickFirstParam(CHARACTER_NAMES, allParams);
  const audioParam = pickFirstParam(AUDIO_NAMES, allParams);
  const videoParam = pickFirstParam(VIDEO_INPUT_NAMES, allParams);

  const supportsGenerateAudio = allSet.has('generate_audio');
  const hasDuration = allSet.has('duration');
  const hasResolution = allSet.has('resolution');
  const hasAspectRatio = allSet.has('aspect_ratio');
  const hasFps = allSet.has('fps');
  const hasNumFrames = allSet.has('num_frames');
  const hasVideoSize = allSet.has('video_size');
  const durationsEnum = Array.isArray(row.durations_enum) ? row.durations_enum.map(String) : [];

  // Detect duration format from enum entries: '8s', '8.0', '8'.
  let durationFormat = 'int';
  if (durationsEnum.length) {
    const sample = durationsEnum[0];
    if (/s$/.test(sample)) durationFormat = 'suffix-s';
    else if (sample.includes('.')) durationFormat = 'float';
  }

  function formatDuration(seconds) {
    const n = Number(seconds);
    if (!Number.isFinite(n) || n <= 0) return null;
    if (durationFormat === 'suffix-s') return `${Math.round(n)}s`;
    if (durationFormat === 'float') return String(n.toFixed(1));
    // Integer-valued durations still ship as a STRING: fal types `duration` as
    // a string literal enum on Kling/Sora/etc. ('3'..'15'), and Pydantic's lax
    // mode coerces "7"->7 for the rare int-typed field. A bare JS number, by
    // contrast, fails the string-literal models with a 422. This matches every
    // hand-registered model, all of which stringify duration.
    return String(Math.round(n));
  }

  // Default duration: prefer the largest enum value if the API enforces one;
  // otherwise leave null (the orchestrator falls back to storyboard / 5s).
  const defaultDuration = durationsEnum.length ? durationsEnum[durationsEnum.length - 1] : null;

  function buildInput(bundle) {
    const input = { prompt: capPrompt(bundle.prompt) || 'Cinematic shot.' };
    if (startParam && bundle.startFrameUrl) input[startParam] = bundle.startFrameUrl;
    if (endParam && bundle.endFrameUrl) input[endParam] = bundle.endFrameUrl;
    if (charParam && bundle.characterSheetUrl) input[charParam] = bundle.characterSheetUrl;
    if (audioParam && bundle.audioUrl) {
      input[audioParam] = isListParam(audioParam) ? [bundle.audioUrl] : bundle.audioUrl;
    }
    if (videoParam && bundle.videoUrl) {
      input[videoParam] = isListParam(videoParam) ? [bundle.videoUrl] : bundle.videoUrl;
    }
    if (refParam && Array.isArray(bundle.referenceImageUrls) && bundle.referenceImageUrls.length) {
      // Array-typed params (plural names) take the whole list; singular ones one URL.
      input[refParam] = isListParam(refParam)
        ? bundle.referenceImageUrls
        : bundle.referenceImageUrls[0];
    }
    if (hasDuration) {
      const formatted = formatDuration(bundle.durationSeconds);
      if (formatted != null) input.duration = formatted;
    }
    if (hasResolution && bundle.resolution) {
      input.resolution = String(bundle.resolution);
    }
    if (hasAspectRatio && bundle.aspectRatio) {
      input.aspect_ratio = String(bundle.aspectRatio);
    }
    if (hasFps && Number.isFinite(Number(bundle.fps)) && Number(bundle.fps) > 0) {
      input.fps = Math.round(Number(bundle.fps));
    }
    if (hasNumFrames) {
      const f = Number(bundle.fps);
      const d = Number(bundle.durationSeconds);
      if (Number.isFinite(f) && f > 0 && Number.isFinite(d) && d > 0) {
        input.num_frames = Math.max(1, Math.round(f * d));
      }
    }
    if (hasVideoSize && bundle.resolution) {
      const dims = resolutionToDims(bundle.resolution);
      if (dims) input.video_size = { width: dims[0], height: dims[1] };
    }
    if (supportsGenerateAudio) input.generate_audio = Boolean(bundle.generateAudio);
    return input;
  }

  function extractVideoUrl(data) {
    return (
      data?.video?.url ||
      data?.output?.url ||
      (typeof data?.output === 'string' ? data.output : null) ||
      data?.video_url ||
      data?.videos?.[0]?.url ||
      null
    );
  }

  return {
    id: row.endpoint_id,
    label: row.display_name || row.endpoint_id,
    falModel: row.endpoint_id,
    description:
      [row.model_lab, row.model_family].filter(Boolean).join(' · ') ||
      `Auto-wired from catalog. Required: ${required.join(', ') || '(none)'}.`,
    durations: durationsEnum,
    defaultDuration,
    supportsGenerateAudio,
    inputs: row.inputs || { ...DEFAULT_CATALOG_INPUTS },
    buildInput,
    extractVideoUrl,
    _synthetic: true,
  };
}

// Cache synthesized models so repeated jobs don't rebuild. Cleared at module
// scope so tests using `_resetForTests()` (none today, but easy to add) can
// reset; the catalog itself is also cheap to re-read so the cache is purely
// a per-process optimization.
const SYNTH_CACHE = new Map();

// Async lookup that consults the registry first, then falls back to the
// catalog manifest for endpoints in allowlisted families with generic-
// wireable inputs. Returns null when the id is unknown OR known but not
// auto-wireable (callers should treat both as "preview not ready").
// Look up catalog metadata (lab/family/added_at, resolutions, …) for a
// given fal endpoint id. Returns null when the catalog isn't generated
// or the endpoint isn't in it. Used by the orchestrator to snapshot
// release info onto the persisted storyboard at generation time.
export async function getVideoModelCatalogMeta(endpointId) {
  if (!endpointId) return null;
  const cat = await loadCatalog();
  const row = cat?.models?.find?.(
    (m) => m.endpoint_id === endpointId || m.id === endpointId,
  );
  if (!row) return null;
  return {
    endpoint_id: row.endpoint_id,
    display_name: row.display_name || null,
    model_lab: row.model_lab || null,
    model_family: row.model_family || null,
    added_at: row.added_at || null,
    resolutions: row.resolutions || [],
    pricing: row.pricing || null,
  };
}

// Per-endpoint audio input constraints that the generic catalog wiring can't
// infer from OpenAPI. Keyed by fal endpoint id. `maxAudioSeconds` drives the
// submit-time trim (src/web/falVideoGenerate.js) and the Generate Video dialog
// notice; `format` documents the required container (enforced globally by the
// upload routes, which normalize all audio to MP3). Explicit — never derived
// from the model's video `max_seconds` — so we don't trim audio for an
// unrelated model whose video duration cap happens to be short.
const AUDIO_CONSTRAINTS = {
  'bytedance/seedance-2.0/reference-to-video': { format: 'mp3', maxAudioSeconds: 15 },
  'bytedance/seedance-2.0/fast/reference-to-video': { format: 'mp3', maxAudioSeconds: 15 },
  // omnihuman v1.5 caps audio length by the chosen output resolution: 60s at
  // 720p, 30s at 1080p. `maxAudioSeconds` is the conservative fallback used
  // when the resolution is unknown; getMaxAudioSeconds() prefers the
  // per-resolution value. (Note the full `fal-ai/` prefix — unlike seedance,
  // omnihuman's catalog endpoint id carries it, and the trim path keys off
  // model.falModel.)
  'fal-ai/bytedance/omnihuman/v1.5': {
    format: 'mp3',
    maxAudioSeconds: 30,
    maxAudioSecondsByResolution: { '720p': 60, '1080p': 30 },
  },
};

export function getAudioConstraints(endpointId) {
  return (endpointId && AUDIO_CONSTRAINTS[endpointId]) || null;
}

// Effective audio-length cap for an endpoint at a given output resolution.
// Returns the per-resolution value when the constraint declares one and the
// resolution matches, else the constraint's flat maxAudioSeconds, else null.
export function getMaxAudioSeconds(endpointId, resolution = null) {
  const c = getAudioConstraints(endpointId);
  if (!c) return null;
  const byRes = c.maxAudioSecondsByResolution;
  if (byRes && resolution != null) {
    const key = String(resolution).toLowerCase();
    if (byRes[key] != null) return byRes[key];
  }
  return c.maxAudioSeconds ?? null;
}

export async function getVideoModelOrCatalog(id) {
  const registered = getVideoModel(id);
  if (registered) return registered;
  if (!id) return null;
  if (SYNTH_CACHE.has(id)) return SYNTH_CACHE.get(id);
  const cat = await loadCatalog();
  const row = cat.models.find((m) => m.endpoint_id === id);
  if (!row) return null;
  if (!isAllowedFamily(id)) return null;
  if (!canGenericWire(row)) return null;
  const model = synthesizeCatalogModel(row);
  SYNTH_CACHE.set(id, model);
  return model;
}

// Default `inputs` shape used when a catalog entry doesn't specify one
// (defensive — newer manifests always include it).
const DEFAULT_CATALOG_INPUTS = Object.freeze({
  startFrame: INPUT_NEEDS.UNUSED,
  endFrame: INPUT_NEEDS.UNUSED,
  characterSheet: INPUT_NEEDS.UNUSED,
  referenceImages: INPUT_NEEDS.UNUSED,
  audio: INPUT_NEEDS.UNUSED,
  videoInput: INPUT_NEEDS.UNUSED,
});

// Map a registered VIDEO_MODELS entry into the SPA-facing dialog shape (no
// buildInput / extractVideoUrl, but all the picker metadata).
function registryToDialogShape(m) {
  return {
    id: m.id,
    label: m.label,
    description: m.description,
    durations: m.durations,
    default_duration: m.defaultDuration,
    supports_generate_audio: m.supportsGenerateAudio,
    inputs: m.inputs,
    pricing: m.pricingId ? describePricing(m.pricingId) : null,
  };
}

// Merge a catalog row + (optional) registered VIDEO_MODELS entry into the
// dialog row shape. Registered fields win over catalog ones because the
// registry's hand-tuned description / duration list is more useful in the
// dropdown than the raw OpenAPI extraction.
//
// Rows in CATALOG_READY_PREFIXES whose required params are all in our
// name-sets get promoted to is_registered=true with id=endpoint_id; the
// orchestrator resolves these via getVideoModelOrCatalog() at submit time.
function mergeCatalogRow(catalogRow, registered) {
  const catalogPricing = catalogPricingFor(catalogRow);
  // Plain-text description harvested from fal at refresh time. Auto-wired and
  // preview rows surface this so the picker isn't a wall of unlabeled ids;
  // hand-registered entries override below.
  const catalogDescription =
    typeof catalogRow.description === 'string' && catalogRow.description.trim()
      ? catalogRow.description.trim()
      : null;
  const base = {
    endpoint_id: catalogRow.endpoint_id,
    display_name: catalogRow.display_name,
    model_lab: catalogRow.model_lab,
    model_family: catalogRow.model_family,
    capabilities: catalogRow.capabilities,
    capability_score: catalogRow.capability_score,
    resolutions: catalogRow.resolutions || [],
    aspect_ratios: catalogRow.aspect_ratios || [],
    max_seconds: catalogRow.max_seconds,
    max_seconds_source: catalogRow.max_seconds_source,
    durations_enum: catalogRow.durations_enum || [],
    supports_generate_audio: Boolean(catalogRow.supports_generate_audio),
    audio_max_seconds: getAudioConstraints(catalogRow.endpoint_id)?.maxAudioSeconds ?? null,
    price_text: catalogRow.price_text || null,
    price_min_usd: catalogRow.price_min_usd ?? null,
    pricing: catalogPricing,
    inputs: catalogRow.inputs || { ...DEFAULT_CATALOG_INPUTS },
    inputs_required: Array.isArray(catalogRow.inputs_required) ? catalogRow.inputs_required : [],
    inputs_optional: Array.isArray(catalogRow.inputs_optional) ? catalogRow.inputs_optional : [],
    added_at: catalogRow.added_at || null,
    is_registered: false,
    id: null,
    label: catalogRow.display_name,
    description: catalogDescription,
    durations: catalogRow.durations_enum || [],
    default_duration: null,
  };
  if (registered) {
    const r = registryToDialogShape(registered);
    return {
      ...base,
      is_registered: true,
      id: r.id,
      label: r.label,
      // Hand-written description in src/fal/videoModels.js wins over the
      // catalog blurb (more useful — explains intent, not just lab/family).
      description: r.description || catalogDescription,
      durations: r.durations,
      default_duration: r.default_duration,
      supports_generate_audio: r.supports_generate_audio,
      inputs: r.inputs,
      pricing: r.pricing || catalogPricing,
    };
  }
  if (isAllowedFamily(catalogRow.endpoint_id) && canGenericWire(catalogRow)) {
    return {
      ...base,
      is_registered: true,
      id: catalogRow.endpoint_id,
      description:
        catalogDescription ||
        [catalogRow.model_lab, catalogRow.model_family].filter(Boolean).join(' · ') ||
        'Auto-wired from catalog.',
    };
  }
  return base;
}

// Best-effort structured pricing for a catalog row that isn't in the
// registered PRICING table. Returns null when price_text is missing or
// unparseable.
function catalogPricingFor(catalogRow) {
  if (!catalogRow?.price_text) return null;
  const parsed = parseCatalogPriceText(catalogRow.price_text);
  if (!parsed) return null;
  const noteBase = `Parsed from price_text: ${parsed.basis}`;
  // Use the catalog's first declared resolution as the default tier when
  // the model is per-second-tiered or per-megapixel (so the SPA renders
  // a non-empty estimate before the user touches the picker).
  const defaultResolution =
    Array.isArray(catalogRow.resolutions) && catalogRow.resolutions.length
      ? catalogRow.resolutions.find((r) => r && r !== 'auto') || null
      : null;
  if (parsed.kind === 'per_second_tiered') {
    return {
      pricing_id: null,
      kind: 'per_second_tiered',
      rates: parsed.rates,
      per_second_usd: null,
      default_resolution: defaultResolution || parsed.rates[0]?.when?.resolution || null,
      requires_audio_duration: false,
      requires_resolution: true,
      requires_fps: false,
      exact: false,
      note: noteBase,
    };
  }
  if (parsed.kind === 'per_second') {
    return {
      pricing_id: null,
      kind: 'per_second',
      rates: [{ when: {}, perSecondUsd: parsed.perSecondUsd }],
      per_second_usd: parsed.perSecondUsd,
      default_resolution: null,
      requires_audio_duration: false,
      requires_resolution: false,
      requires_fps: false,
      exact: false,
      note: noteBase,
    };
  }
  if (parsed.kind === 'per_megapixel') {
    return {
      pricing_id: null,
      kind: 'per_megapixel',
      rates: null,
      per_mp_usd: parsed.perMpUsd,
      default_resolution: defaultResolution,
      default_fps: 24,
      requires_audio_duration: false,
      requires_resolution: true,
      requires_fps: true,
      exact: false,
      note: noteBase,
    };
  }
  if (parsed.kind === 'flat_per_clip') {
    return {
      pricing_id: null,
      kind: 'flat_per_clip',
      rates: null,
      flat_usd: parsed.flatUsd,
      per_second_usd: null,
      default_resolution: null,
      requires_audio_duration: false,
      requires_resolution: false,
      requires_fps: false,
      exact: false,
      note: noteBase,
    };
  }
  return null;
}

// Stub-shape catalog row for a registered model that isn't in the manifest
// (e.g. data/fal-models.json never generated, or the model was hand-added).
function registryStubRow(m) {
  return {
    endpoint_id: m.falModel,
    display_name: m.label,
    model_lab: null,
    model_family: null,
    capabilities: capabilitiesFromInputs(m.inputs),
    capability_score: capabilityScoreFromInputs(m.inputs),
    resolutions: [],
    aspect_ratios: [],
    max_seconds: null,
    max_seconds_source: null,
    durations_enum: Array.isArray(m.durations) ? m.durations.map(String) : [],
    supports_generate_audio: Boolean(m.supportsGenerateAudio),
    price_text: null,
    price_min_usd: null,
    inputs: m.inputs,
  };
}

function capabilitiesFromInputs(inputs) {
  const i = inputs || {};
  const usesSheet = i.characterSheet === INPUT_NEEDS.REQUIRED || i.characterSheet === INPUT_NEEDS.OPTIONAL;
  const usesAudio = i.audio === INPUT_NEEDS.REQUIRED || i.audio === INPUT_NEEDS.OPTIONAL;
  const usesVideoInput = i.videoInput === INPUT_NEEDS.REQUIRED || i.videoInput === INPUT_NEEDS.OPTIONAL;
  return {
    start_frame: i.startFrame === INPUT_NEEDS.REQUIRED || i.startFrame === INPUT_NEEDS.OPTIONAL,
    end_frame: i.endFrame === INPUT_NEEDS.REQUIRED || i.endFrame === INPUT_NEEDS.OPTIONAL,
    reference_images: i.referenceImages === INPUT_NEEDS.REQUIRED || i.referenceImages === INPUT_NEEDS.OPTIONAL,
    character_sheet: usesSheet,
    // lip_sync = audio input but NOT also a source video. Models that take
    // both video + audio (e.g. sync-lipsync v2) surface via the dedicated
    // video_input facet so they don't muddle the avatar-style picker.
    lip_sync: usesAudio && !usesVideoInput,
    video_input: usesVideoInput,
  };
}

function capabilityScoreFromInputs(inputs) {
  const c = capabilitiesFromInputs(inputs);
  return Object.values(c).filter(Boolean).length;
}

// Read the catalog manifest from disk and merge against VIDEO_MODELS. Returns
// `{ generated_at, catalog_error, models: [...] }`. Cheap enough (~200 KB
// JSON parse) to run per request — no in-memory cache for MVP.
export async function loadCatalog() {
  let catalog = null;
  let catalogError = null;
  try {
    const text = await readFile(CATALOG_PATH, 'utf8');
    catalog = JSON.parse(text);
  } catch (e) {
    if (e?.code === 'ENOENT') {
      catalogError = 'Catalog not generated yet. Run: npm run refresh:fal-models';
    } else {
      catalogError = `Catalog read failed: ${e.message}`;
    }
  }

  const registryByEndpoint = new Map(VIDEO_MODELS.map((m) => [m.falModel, m]));
  const seenEndpoints = new Set();
  const out = [];

  if (catalog?.models?.length) {
    for (const row of catalog.models) {
      const registered = registryByEndpoint.get(row.endpoint_id) || null;
      out.push(mergeCatalogRow(row, registered));
      seenEndpoints.add(row.endpoint_id);
    }
  }
  // Append registered models not present in the manifest (defensive — also
  // the no-catalog fallback: every registry entry surfaces as a Ready row).
  for (const m of VIDEO_MODELS) {
    if (seenEndpoints.has(m.falModel)) continue;
    out.push(mergeCatalogRow(registryStubRow(m), m));
  }

  return {
    generated_at: catalog?.generated_at || null,
    catalog_error: catalogError,
    models: out,
  };
}
