import { readFile } from 'node:fs/promises';
import path from 'node:path';

// Registry of fal.ai video models exposed to the SPA's "Generate video"
// dialog. Each entry knows:
//   - which fal model id to call
//   - which storyboard inputs it consumes (required vs optional vs unused)
//   - how to assemble the input payload from already-uploaded fal URLs
//   - how to read the video URL back out of the result
//
// Adding a new model is a one-entry change: drop a record below, expose the
// id in the SPA picker, done. The orchestrator (src/web/falVideoGenerate.js)
// never branches on model id.
//
// The wider universe of fal.ai image-to-video endpoints (188 of them at last
// snapshot) is described by data/fal-models.json, regenerated by
// `npm run refresh:fal-models`. The SPA picker shows that whole catalog and
// flags entries that are wired up here (`is_registered: true`); others show
// as "Preview" and can't be submitted until someone adds a registry entry
// below. loadCatalog() at the bottom of this file merges the two.

export const INPUT_NEEDS = Object.freeze({
  REQUIRED: 'required',
  OPTIONAL: 'optional',
  UNUSED: 'unused',
});

// Maximum number of character "elements" we'll pass to Kling 3 Pro. The
// model's docs cap at a small number; we cap at 4 to match Kling's
// reference docs and to keep prompt size sane.
const MAX_ELEMENTS = 4;

// Cap a prompt to a model's documented hard limit. fal returns a validation
// error on long prompts; we silently truncate so a too-long text_prompt
// never blocks a render. Kling docs mention 2000 chars; we keep 1500 as a
// safety margin shared across models.
const PROMPT_HARD_CAP = 2000;
function capPrompt(s) {
  const t = String(s || '').trim();
  return t.length > PROMPT_HARD_CAP ? t.slice(0, PROMPT_HARD_CAP) : t;
}

// Map our input bundle to a "video URL" payload shape that every model in
// this registry can stitch from. The orchestrator hands every model the
// same bundle; each model picks the fields it needs.
//
// The bundle:
//   prompt:                string (markdown stripped, fal-cap applied)
//   startFrameUrl:         fal URL of storyboard.start_frame_id image
//   endFrameUrl:           fal URL of storyboard.end_frame_id image (or null)
//   characterSheetUrl:     fal URL of storyboard.character_sheet_image_id (or null)
//   characterElements:     [{ frontalUrl, referenceUrls: [] }] built from
//                          each character in characters_in_scene (capped)
//   referenceImageUrls:    fal URLs for each storyboard.reference_image_ids[]
//   audioUrl:              fal URL of storyboard.audio_file_id (or null)
//   durationSeconds:       integer 1..15
//   generateAudio:         boolean (only honored by models that support it)

export const VIDEO_MODELS = [
  {
    id: 'kling-3-pro',
    label: 'Kling 3 Pro',
    falModel: 'fal-ai/kling-video/v3/pro/image-to-video',
    description:
      'Image-to-video with start frame, optional end frame, character elements ' +
      '(built from characters_in_scene), and native audio synthesis from the prompt.',
    // Kling 3 Pro accepts integer-string durations 3..15.
    durations: ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'],
    defaultDuration: '5',
    supportsGenerateAudio: true,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.OPTIONAL,
      characterSheet: INPUT_NEEDS.UNUSED,
      characterElements: INPUT_NEEDS.OPTIONAL,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      const input = {
        prompt: capPrompt(bundle.prompt) || 'Cinematic shot.',
        start_image_url: bundle.startFrameUrl,
        duration: String(bundle.durationSeconds || 5),
        generate_audio: Boolean(bundle.generateAudio),
      };
      if (bundle.endFrameUrl) input.end_image_url = bundle.endFrameUrl;
      const elements = (bundle.characterElements || []).slice(0, MAX_ELEMENTS).map((el) => {
        const out = { frontal_image_url: el.frontalUrl };
        if (Array.isArray(el.referenceUrls) && el.referenceUrls.length) {
          out.reference_image_urls = el.referenceUrls;
        }
        return out;
      });
      if (elements.length) input.elements = elements;
      return input;
    },
    extractVideoUrl(data) {
      return data?.video?.url || data?.output || null;
    },
  },

  {
    id: 'veo-3-1-flf',
    label: 'Veo 3.1 (first-last-frame)',
    falModel: 'fal-ai/veo3.1/first-last-frame-to-video',
    description:
      'Best-in-class motion quality. Requires both start and end frames. ' +
      'Audio is generated from the prompt; cannot consume an input audio file.',
    durations: ['4', '6', '8'],
    defaultDuration: '8',
    supportsGenerateAudio: true,
    inputs: {
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.REQUIRED,
      characterSheet: INPUT_NEEDS.UNUSED,
      characterElements: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.UNUSED,
    },
    buildInput(bundle) {
      return {
        prompt: capPrompt(bundle.prompt) || 'Cinematic shot.',
        first_frame_url: bundle.startFrameUrl,
        last_frame_url: bundle.endFrameUrl,
        duration: `${bundle.durationSeconds || 8}s`,
        generate_audio: Boolean(bundle.generateAudio),
      };
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },

  {
    id: 'kling-avatar-v2-pro',
    label: 'Kling AI Avatar v2 Pro (lip-sync)',
    falModel: 'fal-ai/kling-video/ai-avatar/v2/pro',
    description:
      'True lip-sync. Takes one anchor image plus an audio file and animates a ' +
      'talking head matched to the audio. Ignores end frame and character elements.',
    // Duration follows the input audio length; the API has no duration knob.
    durations: [],
    defaultDuration: null,
    supportsGenerateAudio: false,
    inputs: {
      // Anchor image: the orchestrator prefers character_sheet_image_id when
      // present (closer crop of the speaking subject), else falls back to
      // start_frame_id. We mark startFrame REQUIRED so storyboards without
      // either anchor get rejected with a clear message.
      startFrame: INPUT_NEEDS.REQUIRED,
      endFrame: INPUT_NEEDS.UNUSED,
      characterSheet: INPUT_NEEDS.OPTIONAL,
      characterElements: INPUT_NEEDS.UNUSED,
      referenceImages: INPUT_NEEDS.UNUSED,
      audio: INPUT_NEEDS.REQUIRED,
    },
    buildInput(bundle) {
      const input = {
        image_url: bundle.characterSheetUrl || bundle.startFrameUrl,
        audio_url: bundle.audioUrl,
      };
      const prompt = capPrompt(bundle.prompt);
      if (prompt) input.prompt = prompt;
      return input;
    },
    extractVideoUrl(data) {
      return data?.video?.url || null;
    },
  },
];

const MODELS_BY_ID = new Map(VIDEO_MODELS.map((m) => [m.id, m]));

export function getVideoModel(id) {
  return MODELS_BY_ID.get(String(id)) || null;
}

// Inputs the SPA dialog can use to drive UI affordances without re-deriving
// shape per model. Returns null when the id isn't registered.
export function describeVideoModel(id) {
  const m = getVideoModel(id);
  if (!m) return null;
  return {
    id: m.id,
    label: m.label,
    description: m.description,
    durations: m.durations,
    defaultDuration: m.defaultDuration,
    supportsGenerateAudio: m.supportsGenerateAudio,
    inputs: m.inputs,
  };
}

// Storyboard fields each input maps to; used by validateInputs and by the
// orchestrator when assembling the bundle.
const INPUT_TO_FIELD = Object.freeze({
  startFrame: 'start_frame_id',
  endFrame: 'end_frame_id',
  characterSheet: 'character_sheet_image_id',
  audio: 'audio_file_id',
});

// Human-readable label for missing-input errors.
const INPUT_LABEL = Object.freeze({
  startFrame: 'start frame',
  endFrame: 'end frame',
  characterSheet: 'character sheet',
  audio: 'audio',
});

// Validate that a storyboard has the inputs a chosen model requires.
// Returns an array of human-readable missing labels (empty when OK).
export function validateStoryboardInputs(model, storyboard) {
  const missing = [];
  for (const [inputKey, need] of Object.entries(model.inputs)) {
    if (need !== INPUT_NEEDS.REQUIRED) continue;
    const field = INPUT_TO_FIELD[inputKey];
    if (!field) continue; // characterElements/referenceImages have no single storyboard field
    if (!storyboard[field]) missing.push(INPUT_LABEL[inputKey] || inputKey);
  }
  return missing;
}

// ---------------------------------------------------------------------------
// Catalog (data/fal-models.json) — the wide list of i2v fal endpoints the SPA
// picker browses. Most catalog entries are "Preview" (no registry wiring);
// the few in VIDEO_MODELS are "Ready" and selectable for generation.

const CATALOG_PATH = path.join(process.cwd(), 'data', 'fal-models.json');

// Default `inputs` shape used when a catalog entry doesn't specify one
// (defensive — newer manifests always include it).
const DEFAULT_CATALOG_INPUTS = Object.freeze({
  startFrame: INPUT_NEEDS.UNUSED,
  endFrame: INPUT_NEEDS.UNUSED,
  characterSheet: INPUT_NEEDS.UNUSED,
  characterElements: INPUT_NEEDS.UNUSED,
  referenceImages: INPUT_NEEDS.UNUSED,
  audio: INPUT_NEEDS.UNUSED,
});

// Map a registered VIDEO_MODELS entry into the SPA-facing dialog shape (no
// buildInput / extractVideoUrl, but all the picker metadata).
function registryToDialogShape(m) {
  return {
    id: m.id,
    label: m.label,
    description: m.description,
    durations: m.durations,
    default_duration: m.defaultDuration,
    supports_generate_audio: m.supportsGenerateAudio,
    inputs: m.inputs,
  };
}

// Merge a catalog row + (optional) registered VIDEO_MODELS entry into the
// dialog row shape. Registered fields win over catalog ones because the
// registry's hand-tuned description / duration list is more useful in the
// dropdown than the raw OpenAPI extraction.
function mergeCatalogRow(catalogRow, registered) {
  const base = {
    endpoint_id: catalogRow.endpoint_id,
    display_name: catalogRow.display_name,
    model_lab: catalogRow.model_lab,
    model_family: catalogRow.model_family,
    capabilities: catalogRow.capabilities,
    capability_score: catalogRow.capability_score,
    resolutions: catalogRow.resolutions || [],
    aspect_ratios: catalogRow.aspect_ratios || [],
    max_seconds: catalogRow.max_seconds,
    max_seconds_source: catalogRow.max_seconds_source,
    durations_enum: catalogRow.durations_enum || [],
    supports_generate_audio: Boolean(catalogRow.supports_generate_audio),
    price_text: catalogRow.price_text || null,
    price_min_usd: catalogRow.price_min_usd ?? null,
    inputs: catalogRow.inputs || { ...DEFAULT_CATALOG_INPUTS },
    is_registered: false,
    id: null,
    label: catalogRow.display_name,
    description: null,
    durations: catalogRow.durations_enum || [],
    default_duration: null,
  };
  if (registered) {
    const r = registryToDialogShape(registered);
    return {
      ...base,
      is_registered: true,
      id: r.id,
      label: r.label,
      description: r.description,
      durations: r.durations,
      default_duration: r.default_duration,
      supports_generate_audio: r.supports_generate_audio,
      inputs: r.inputs,
    };
  }
  return base;
}

// Stub-shape catalog row for a registered model that isn't in the manifest
// (e.g. data/fal-models.json never generated, or the model was hand-added).
function registryStubRow(m) {
  return {
    endpoint_id: m.falModel,
    display_name: m.label,
    model_lab: null,
    model_family: null,
    capabilities: capabilitiesFromInputs(m.inputs),
    capability_score: capabilityScoreFromInputs(m.inputs),
    resolutions: [],
    aspect_ratios: [],
    max_seconds: null,
    max_seconds_source: null,
    durations_enum: Array.isArray(m.durations) ? m.durations.map(String) : [],
    supports_generate_audio: Boolean(m.supportsGenerateAudio),
    price_text: null,
    price_min_usd: null,
    inputs: m.inputs,
  };
}

function capabilitiesFromInputs(inputs) {
  const i = inputs || {};
  return {
    start_frame: i.startFrame === INPUT_NEEDS.REQUIRED || i.startFrame === INPUT_NEEDS.OPTIONAL,
    end_frame: i.endFrame === INPUT_NEEDS.REQUIRED || i.endFrame === INPUT_NEEDS.OPTIONAL,
    reference_images: i.referenceImages === INPUT_NEEDS.REQUIRED || i.referenceImages === INPUT_NEEDS.OPTIONAL,
    character_sheet: i.characterSheet === INPUT_NEEDS.REQUIRED || i.characterSheet === INPUT_NEEDS.OPTIONAL,
    lip_sync: i.audio === INPUT_NEEDS.REQUIRED || i.audio === INPUT_NEEDS.OPTIONAL,
  };
}

function capabilityScoreFromInputs(inputs) {
  const c = capabilitiesFromInputs(inputs);
  return Object.values(c).filter(Boolean).length;
}

// Read the catalog manifest from disk and merge against VIDEO_MODELS. Returns
// `{ generated_at, catalog_error, models: [...] }`. Cheap enough (~200 KB
// JSON parse) to run per request — no in-memory cache for MVP.
export async function loadCatalog() {
  let catalog = null;
  let catalogError = null;
  try {
    const text = await readFile(CATALOG_PATH, 'utf8');
    catalog = JSON.parse(text);
  } catch (e) {
    if (e?.code === 'ENOENT') {
      catalogError = 'Catalog not generated yet. Run: npm run refresh:fal-models';
    } else {
      catalogError = `Catalog read failed: ${e.message}`;
    }
  }

  const registryByEndpoint = new Map(VIDEO_MODELS.map((m) => [m.falModel, m]));
  const seenEndpoints = new Set();
  const out = [];

  if (catalog?.models?.length) {
    for (const row of catalog.models) {
      const registered = registryByEndpoint.get(row.endpoint_id) || null;
      out.push(mergeCatalogRow(row, registered));
      seenEndpoints.add(row.endpoint_id);
    }
  }
  // Append registered models not present in the manifest (defensive — also
  // the no-catalog fallback: every registry entry surfaces as a Ready row).
  for (const m of VIDEO_MODELS) {
    if (seenEndpoints.has(m.falModel)) continue;
    out.push(mergeCatalogRow(registryStubRow(m), m));
  }

  return {
    generated_at: catalog?.generated_at || null,
    catalog_error: catalogError,
    models: out,
  };
}
